---
shared:
  image: node:14
jobs:
  main:
    requires: [~pr, ~commit]
    steps:
    - install_prerequisites: npm install -g screwdriver-template-main
    - validate_default-namespace_template: |
        template-validate

  publish_default-namespace_template:
    requires: [main]
    steps:
    - install_prerequisites: npm install -g screwdriver-template-main
    - publish:  template-publish
