---
shared:
  image: node:8
jobs:
  main:
    requires: [~pr, ~commit]
    steps:
    - install_prerequisites: npm install -g screwdriver-template-main
    - validate_no-namespace_template: |
        export SD_TEMPLATE_PATH=./templates/other-template.yaml
        template-validate

  publish_no-namespace_template:
    requires: [main]
    environment:
      SD_TEMPLATE_PATH: ./templates/other-template.yaml
    steps:
    - install_prerequisites: npm install -g screwdriver-template-main
    - publish:  template-publish 
