shared:
    image: node:12
    
jobs:
#     main:
#         requires: [~commit]
#         steps:
#               - hello: sleep 10
    main:
        requires: [~commit]
        annotations:
            screwdriver.cd/buildPeriodically: 20 1 * * *
        steps:
              - hello: sleep 10
#     job1:
#         requires: [~commit]
#         annotations:
#             screwdriver.cd/buildPeriodically: 20 2 * * *
#         steps:
#               - hello: sleep 10
#     job2:
#         requires: [~commit]
#         annotations:
#             screwdriver.cd/buildPeriodically: 20 2 * * *
#         steps:
#               - hello: sleep 10
#     prjob:
#         requires: [~pr]
#         steps:
#             - hello: echo hi
#     test:
#         requires: [main]
#         steps:
#             - hello: echo hii
#     end:
#         requires: [test]
#         steps:
#             - hello: echo hii
