shared:
    image: node:18
jobs:
    main:
        requires: [~commit]
        steps:
              - hello: meta set meta.test.meta "a meta"
     test:
         requires: [main]
         steps:
             - hello: echo hii

