shared:
    image: node:12
    
jobs:
    main:
        requires: [~commit]
        annotations:
            screwdriver.cd/blockedBySameJob: false
            screwdriver.cd/blockedBySameJobWaitTime: 0
        steps:
              - hello: sleep 500
#     prjob:
#         requires: [~pr]
#         steps:
#             - hello: echo hi
#     test:
#         requires: [main]
#         steps:
#             - hello: echo hii
#     end:
#         requires: [test]
#         steps:
#             - hello: echo hii
