shared:
    image: node:18
jobs:
    main:
        requires: [~commit]
        steps:
            - hello: meta set meta.test.meta "a meta"
    test:
        requires: [main]
        freezeWindows: ['* 17-24 ? * *']
        steps:
            - hello: meta get meta.test.meta
    test2:
        requires: [test]
        steps:
            - hello: meta get meta.test.meta
    test3:
        requires: [test]
        steps:
            - hello: meta get meta.test.meta
